### ISSUE TITLE
Using PersonCard in version `3.0.0-beta.17` causes app to become unresponsive

### ISSUE THREAD

**Issue by v3gard** [equinor/fusion-cli#850]
As mentioned in the title, using the `<PersonCard/>` component causes the app to become unresponsive when the mouse cursor is hovered over the loaded PersonDetails instance to see the Popover component.

# How to reproduce
1. Create a new fusion app with fusion-cli.
2. Load the app with registerApp (i.e. legacy mode)
3. Load some person details with the `usePersonDetails` hook.
4. Render the person details in a `<PersonCard/>`
5. Start the app, move the cursor to the `<PersonCard/>` component and wait for the app to become unresponsive.

# Temporary workaround
Downgrade to an earlier version (e.g. 3.0.0.-beta.8).

# Demo
![hanging_app_vanilla](https://user-images.githubusercontent.com/343078/172310579-4ff3cde7-05fc-42ba-b9ab-6b18186cc4f9.gif)

**Comment by odinr** [comment]
check if this is still a bug

**Comment by odinr** [comment]
this bug is/was related to the createPortal, this is not deprecated, there is a new PersonCard component in the fusion-react-components, for now
