### ISSUE TITLE
Using CLI with latest fusion-react-framework outputs warnings

### ISSUE THREAD

**Issue by v3gard** [equinor/fusion-cli#866]
# Versions used
* @equinor/fusion-cli@3.0.0-beta.25
* @equinor/fusion-framework-react-app@1.0.14

# Bug

If you create an application with the fusion-framework-react-app (and legacy bootstrapper), e.g. 
```ts
import { Context, ContextTypes, registerApp as registerAppLegacy } from "@equinor/fusion";
import { createLegacyApp } from "@equinor/fusion-framework-react-app";
import { enableAgGrid } from "@equinor/fusion-framework-module-ag-grid";
import { App } from "./components";

registerAppLegacy("myApp", {
    AppComponent: createLegacyApp(App),
    context: {
        types: [ContextTypes.ProjectMaster],
        buildUrl: (context: Context | null) => {
            return context ? `/${context.id}` : "";
        },
        getContextFromUrl: (url: string) => {
            return url.split("/")[1];
        },
    },
    name: "My App",
});

if (module.hot) module.hot.accept();

```
fusion-cli will output the following

# ![image](https://user-images.githubusercontent.com/343078/195085081-a08d591e-e1d7-49b9-9672-8e8a784f4d22.png)

The app seems to work fine otherwise.

# Expectation

No warnings.

**Comment by odinr** [comment]
think this is releated to the cli has conflicting versions of cli and locally imported fusion-framework.
we are tweaking these deps
