### ISSUE TITLE
Fusion CLI should run in developer mode when running locally

### ISSUE THREAD

**Issue by odinr** [equinor/fusion-cli#870]
[blame](https://github.com/equinor/fusion-cli/commit/d455ff3f3e5d8ac5c1d288b222a2237f620e96e2#r87940550)

- [ ] reinsert dev mode
- [x] test locally
- [x] check build (validate mode is production)

ref: react dev tools fails

**Comment by odinr** [comment]
required asap zulu 😘

**Comment by eikeland** [comment]
Is the issue on the beta releases?
The main release is using dev and production mode  already.
